version: "3.8"

volumes:

  core-static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './core/static/'

services:

  video_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    command: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8802"
    ports:
      - "8802:8802"
    volumes:
      - core-static:/core/static/
